# Generated by Django 3.0.8 on 2020-07-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_n', models.FileField(upload_to='files')),
                ('uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
